import "@/styles/globals.css";
import { Providers } from "./providers";
import Header from "@/layouts/Header";
import MainLayout from "./main";
import Footer from "@/layouts/Footer";
import { AuthProvider } from "@/contexts/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProvider>
            <Header />
            <MainLayout>{children}</MainLayout>
            <Footer />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
