import "@/styles/globals.css";
import { Providers } from "./providers";
import Header from "@/layouts/Header";
import MainLayout from "./main";
import Footer from "@/layouts/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <MainLayout>{children}</MainLayout>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
